image: azul/zulu-openjdk:19

variables:
  CONTAINER_IMAGE: beo1975/book-library-service:latest

stages:
  - test
  - scan

scan-code:
  stage: .pre
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [""]
  script:
    - gitleaks detect --verbose --redact --no-git --source="$CI_PROJECT_DIR"
  rules:
    - if: ($CI_PIPELINE_SOURCE != "schedule")
  tags:
    - docker

scan-vulnerabilities:
  stage: .pre
  image:
    name: "aquasec/trivy:latest"
    entrypoint: [""]
  script:
    - trivy fs --no-progress --ignore-unfixed --exit-code 0 $CI_PROJECT_DIR
  allow_failure: true
  rules:
    - if: ($CI_PIPELINE_SOURCE != "schedule")
  tags:
    - docker

test-code:
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew :app:jacocoTestReport
    - cat app/build/reports/jacoco/test/html/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  rules:
    - if: ($CI_PIPELINE_SOURCE != "schedule")
  tags:
    - docker

scan-image:
  stage: scan
  image:
    name: "aquasec/trivy:latest"
    entrypoint: [""]
  script:
    - trivy i --no-progress --ignore-unfixed --clear-cache --exit-code 1 $CONTAINER_IMAGE
  rules:
    - if: ($CI_PIPELINE_SOURCE == "schedule") && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  tags:
    - docker
