image: azul/zulu-openjdk:19

test-code:
  stage: test
  script:
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  coverage: "/Total.*?([0-9]{1,3})%/"
  tags:
    - docker
