spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            poolId: ${COGNITO_USER_POOL_ID}
            clientId: ${COGNITO_CLIENT_ID}
            clientSecret: ${COGNITO_CLIENT_SECRET}
            scope: openid, profile, email
            clientName: b-l-s-client
        provider:
          cognito:
            issuerUri: ${COGNITO_PROVIDER_URL}

custom:
  use-cognito-as-identity-provider: true
