spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            poolId: stratospheric
            clientId: spring-boot-application
            clientSecret: 27b07baf-53ba-42c6-b11f-6384769cada3
            scope: openid
            clientName: spring-boot-application
            logoutUrl: http://localhost:8888
        provider:
          cognito:
            issuerUri: http://localhost:8888/realms/stratospheric

cloud:
  aws:
    credentials:
      access-key: foo
      secret-key: bar

custom:
  use-cognito-as-identity-provider: false
