spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: book-library-service
            clientSecret: 27b07baf-53ba-42c6-b11f-6384769cada3
            scope: openid, profile, email
            clientName: b-l-s-client
        provider:
          cognito:
            issuerUri: http://localhost:8888/auth/realms/b-l-s

cloud:
  aws:
    credentials:
      access-key: foo
      secret-key: bar

custom:
  use-cognito-as-identity-provider: false
