# This workflow builds the Docker image for the book-library-service and then deploys the application.
name: 04 - Build and deploy the application to DockerHub and to AWS

on:
  workflow_run:
    workflows:
      - '03 - Run application tests'
    types:
      - completed
    branches:
      - master

jobs:
  changes:
    name: Detect relevant source changes
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      app: ${{ steps.filter.outputs.app }}
      gradle-app: ${{ steps.filter.outputs.gradle-app }}
      dockerfile: ${{ steps.filter.outputs.dockerfile }}
      workflow-deploy: ${{ steps.filter.outputs.workflow-deploy }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run changes detection
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          filters: |
            app:
              - 'app/src/main/**'
            gradle-app:
              - 'app/build.gradle.kts'
            dockerfile:
              - 'Dockerfile'
            workflow-deploy:
              - '.github/workflows/04-build-and-deploy-application.yml'

  build-and-publish:
    name: Build and publish the application
    runs-on: ubuntu-22.04
    needs: changes
    if: ${{ needs.changes.outputs.app == 'true' || needs.changes.outputs.gradle-app == 'true' || needs.changes.outputs.dockerfile == 'true' || needs.changes.outputs.workflow-deploy == 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            beo1975/book-library-service:0.1.0
            beo1975/book-library-service:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
